# Generated by Django 4.2 on 2025-06-05 07:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('started', 'Начат'), ('finished', 'Завершён')], default='not_started', max_length=20)),
                ('team_a_score', models.PositiveIntegerField(default=0)),
                ('team_b_score', models.PositiveIntegerField(default=0)),
                ('current_set', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Команда с таким названием уже существует'}, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя игрока')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('position', models.CharField(choices=[('s', 'Setter'), ('oh', 'Outside Hitter'), ('op', 'Opposite'), ('mb', 'Middle Blocker'), ('l', 'Libero')], max_length=2, verbose_name='Позиция')),
                ('zone', models.CharField(max_length=1, verbose_name='Зона')),
                ('team_choice', models.CharField(choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1, verbose_name='Выбор команды')),
                ('is_captain', models.BooleanField(default=False, verbose_name='Капитан')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referee.match', verbose_name='Матч')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='referee.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['team_choice', 'number'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='referee.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='referee.team'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('serve', 'Подача'), ('attack', 'Атака'), ('block', 'Блок'), ('receive', 'Прием'), ('set', 'Пас'), ('dig', 'Защита'), ('error', 'Ошибка'), ('substitution', 'Замена'), ('timeout', 'Тайм-аут')], max_length=12)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referee.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referee.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('match', 'team', 'zone'), name='unique_player_zone_per_team_match'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('match', 'team', 'number'), ('match', 'team', 'zone')},
        ),
    ]
