# Generated by Django 4.2 on 2025-06-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0002_match_team_a_rotation_match_team_b_rotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='zone',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Зона'),
        ),
    ]
