# Generated by Django 4.2 on 2025-06-06 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0003_alter_player_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sets_won_a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='sets_won_b',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='current_set',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('attacks', models.PositiveIntegerField(default=0)),
                ('blocks', models.PositiveIntegerField(default=0)),
                ('perfect_receptions', models.PositiveIntegerField(default=0)),
                ('digs', models.PositiveIntegerField(default=0)),
                ('reception_errors', models.PositiveIntegerField(default=0)),
                ('total_receptions', models.PositiveIntegerField(default=0)),
                ('successful_sets', models.PositiveIntegerField(default=0)),
                ('ace_sets', models.PositiveIntegerField(default=0)),
                ('set_errors', models.PositiveIntegerField(default=0)),
                ('attack_distribution', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referee.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referee.player')),
            ],
        ),
    ]
