# Generated by Django 4.2 on 2025-06-07 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0004_match_sets_won_a_match_sets_won_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='current_set',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
