# Generated by Django 4.2 on 2025-06-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0005_alter_match_current_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='match',
            name='current_set',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a_rotation',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_rotation',
            field=models.JSONField(default=dict),
        ),
    ]
